//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CherP2.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int id { get; set; }
        public string name { get; set; }
        public string opisanie { get; set; }
        public string img
        {
            get { return img; }
            set
            {
                img = $"pack://application:,,,/CherPodgotov;component/Resources/{opisanie}.png";
            }
        }

        public int kolich { get; set; }
        public decimal cena { get; set; }
    }
}
